platform :ios, '7.0'
source 'ssh://git@devops-tools.pearson.com/mp/gridmobile-cocoapods.git'

target "SeerClientApp" do
    pod 'seer-ios-sdk', '1.3.0-SNAPSHOT'
    pod 'core-ios-sdk', '1.2.0'
end

post_install do |installer_representation|
    installer_representation.project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
        end
    end
end
