platform :ios, "7.1"
source 'ssh://git@devops-tools.pearson.com/mp/gridmobile-cocoapods.git'

target "CourseListClient" do
  pod 'core-ios-sdk', '1.2.0'
  pod 'pi-ios-sdk', '1.2.0'
  pod 'classroom-ios-library', '0.1.0-SNAPSHOT'
end
